apiVersion: v1
kind: Service
metadata:
  name: vine-irrigation
  labels:
    app.kubernetes.io/name: vine-irrigation
    app.kubernetes.io/part-of: vine
    vine.nrp.ai/track: irrigation
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: vine-irrigation
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
