"""Generate codemap shards — one markdown file per package under src/vine.

Each shard lists every module's signatures, first docstring lines, and internal
import edges, so a reader (human or agent) can locate code without Reading
source files. Consult shards BEFORE opening source. Regenerate after every
refactor, in the same commit:

    uv run python scripts/codemap.py        # writes docs/codemap/*.md

Shard headers are stamped with the source git hash so staleness is visible.
Stdlib only (ast) — no dependencies.
"""

from __future__ import annotations

import ast
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "src" / "vine"
OUT = ROOT / "docs" / "codemap"


def git_hash() -> str:
    try:
        out = subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"], cwd=ROOT, capture_output=True, text=True
        )
        return out.stdout.strip() or "unknown"
    except OSError:
        return "unknown"


def signature(fn: ast.FunctionDef | ast.AsyncFunctionDef) -> str:
    """Render a def line from its AST node, including annotations and defaults."""
    a = fn.args
    parts: list[str] = []
    pos = a.posonlyargs + a.args
    n_defaults = len(a.defaults)
    for i, arg in enumerate(pos):
        s = arg.arg
        if arg.annotation is not None:
            s += f": {ast.unparse(arg.annotation)}"
        d = i - (len(pos) - n_defaults)
        if d >= 0:
            s += f" = {ast.unparse(a.defaults[d])}"
        parts.append(s)
    if a.posonlyargs:
        parts.insert(len(a.posonlyargs), "/")
    if a.vararg:
        parts.append(f"*{a.vararg.arg}")
    elif a.kwonlyargs:
        parts.append("*")
    for arg, default in zip(a.kwonlyargs, a.kw_defaults, strict=True):
        s = arg.arg
        if arg.annotation is not None:
            s += f": {ast.unparse(arg.annotation)}"
        if default is not None:
            s += f" = {ast.unparse(default)}"
        parts.append(s)
    if a.kwarg:
        parts.append(f"**{a.kwarg.arg}")
    ret = f" -> {ast.unparse(fn.returns)}" if fn.returns is not None else ""
    prefix = "async def" if isinstance(fn, ast.AsyncFunctionDef) else "def"
    return f"{prefix} {fn.name}({', '.join(parts)}){ret}"


def first_doc_line(node: ast.AST) -> str:
    doc = ast.get_docstring(node)  # type: ignore[arg-type]
    return doc.strip().splitlines()[0] if doc else ""


def vine_imports(tree: ast.Module) -> list[str]:
    """Internal import edges (vine.* only) — the dependency structure."""
    edges: set[str] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            edges.update(n.name for n in node.names if n.name.startswith("vine"))
        elif isinstance(node, ast.ImportFrom) and node.module and node.module.startswith("vine"):
            edges.add(node.module)
    return sorted(edges)


def describe_module(path: Path) -> list[str]:
    """Markdown lines for one module: docstring, imports, classes, functions."""
    tree = ast.parse(path.read_text())
    lines = [f"### `{path.relative_to(ROOT)}`"]
    if doc := first_doc_line(tree):
        lines.append(f"*{doc}*")
    if edges := vine_imports(tree):
        lines.append(f"imports: {', '.join(f'`{e}`' for e in edges)}")
    lines.append("")
    for node in tree.body:
        if isinstance(node, ast.ClassDef):
            bases = f"({', '.join(ast.unparse(b) for b in node.bases)})" if node.bases else ""
            lines.append(f"- **class {node.name}{bases}** — {first_doc_line(node)}")
            for item in node.body:
                if isinstance(item, (ast.FunctionDef, ast.AsyncFunctionDef)):
                    lines.append(f"    - `{signature(item)}` — {first_doc_line(item)}".rstrip(" —"))
        elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            lines.append(f"- `{signature(node)}` — {first_doc_line(node)}".rstrip(" —"))
        elif isinstance(node, ast.Assign) and all(
            isinstance(t, ast.Name) and t.id.isupper() for t in node.targets
        ):
            names = ", ".join(t.id for t in node.targets)  # type: ignore[union-attr]
            lines.append(f"- const `{names}`")
    lines.append("")
    return lines


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    stamp = git_hash()
    packages = sorted(p for p in SRC.iterdir() if p.is_dir() and (p / "__init__.py").exists())
    root_modules = sorted(p for p in SRC.glob("*.py"))
    shards: dict[str, list[Path]] = {"vine": root_modules}
    for pkg in packages:
        shards[f"vine.{pkg.name}"] = sorted(pkg.rglob("*.py"))

    for name, modules in shards.items():
        lines = [
            f"# Codemap: `{name}`",
            "",
            f"> Generated by `scripts/codemap.py` at git `{stamp}`. Do not edit;",
            "> regenerate after any refactor (same commit). Consult before Reading source.",
            "",
        ]
        for mod in modules:
            lines += describe_module(mod)
        (OUT / f"{name}.md").write_text("\n".join(lines) + "\n")
        print(f"  wrote docs/codemap/{name}.md ({len(modules)} modules)")


if __name__ == "__main__":
    main()
